services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agri-backend
    ports:
      - "5000:5000"
    volumes:
      - ./ml_models:/ml_models
      - ./datasets:/datasets
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agri-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped